//admin api 
@url= http://localhost:8000/api/v1

POST {{url}}/admin/register
Content-type:application/json

{  
"address": "",
"email": "s@gmail.com",
"fName": "sdf",
"lName": "sdf",
"password": "1233",


"phone": null
}