//admin api 
@url= http://localhost:8000/api/v1

POST {{url}}/admin/register
Content-type:application/json

{  
"address": "",
"email": "s@gmail.com",
"fName": "sdf",
"lName": "sdf",
"password": "1233",


"phone": null
}

#verify user email
#  http://localhost:3000/verify?
c=49d1068b-72b0-427a-b43d-d073577439d6&email=ss@gmail.com