//admin api 
@url= http://localhost:8000/api/v1

POST {{url}}/admin/register
Content-type:application/json

{  
"address": "",
"email": "as@gmail.com",
"fName": "sdf",
"lName": "sdf",
"password": "1233",


"phone": null
}


###login apge

POST {{url}}/admin/login
Content-type:application/json

{  

"email": "sss@gmail.com",
"password": "Rai123"


}
# #verify user email
# #  http://localhost:3000/verify?
# c=49d1068b-72b0-427a-b43d-d073577439d6&email=ss@gmail.com

##======== category api 

### crate new api 
# @catUrl={{url}}

POST {{url}}/category
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNzc0BnbWFpbC5jb20iLCJpYXQiOjE2Nzg2NjgxMzksImV4cCI6MTY3ODY2OTAzOX0.NdEFGBT-6KE1el_-3C7z2CqQO2uhDOcRsZHE1SsdzxY

{
    "name" : "klsj"
}




###
get {{url}}/orders
